config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :bookings, only: [:new, :create, :destroy, :edit, :index]
  resources :products, only: [:new, :create, :index, :show, :edit] do
    resources :bookmarks, only: [:create]
    resources :reviews, only: [:new, :create]
  end
  resources :products, only: [:destroy], as: :delete_products
  
  resources :users do
    resources :bookings, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :product
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewer, class_name: 'User'
  belongs_to :reviewee, class_name: 'User'
  belongs_to :booking
  validates :rating, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo, :description])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo, :description])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    product_id = params["booking"][:product_id]
    @booking = Booking.new(set_params)
    @booking.user_id = current_user.id
    start_date= params["booking"][:start_date]
    end_date= params["booking"][:end_date]
    #@booking.product_id = params["booking"][:product_id]
    start_date_comparision = Date.parse(start_date)
    if end_date < start_date
      redirect_to product_path(product_id), notice: "End date must be after start date."
    elsif start_date_comparision < Date.today
      redirect_to product_path(product_id), notice: "Start date must be after today."
    elsif @booking.save
      redirect_to root_path, notice: "Booking created successfully."
    else
      redirect_to new_user_session_path, alert: "Booking creation failed. Please log in."
    end
  end
  private

  def set_params
    params.require(:booking).permit(:start_date, :end_date, :product_id)
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    @bookmark = Bookmark.new
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.destroy

    redirect_to products_url, notice: "Product deleted."
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update]

  def  index
    @users = User.all
    skill_id = params[:skill_id]
    @request = Request.where(user_id: current_user.id).last
  end

  # def mean
  #   if Review.where(reviewee_id: @user.id) != []
  #     @reviews = Review.where(reviewee_id: @user.id)
  #     ratings = []
  #     @reviews.each do |review|
  #       ratings << review.rating
  #     end
  #     average_rating = ratings.sum / ratings.length.to_f
  #     @user.average_rating = average_rating.truncate(1)
  #     @user.save
  #   end
  # end

  def show
      @user = current_user
      @reviews = Review.where(reviewee_id: @user.id)
      @bookings = Booking.where(user_id: @user.id)
      # mean
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Votre profil a été mis à jour avec succès.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :description, :photo)
    # Ajoutez ici les autres attributs que vous souhaitez permettre de modifier
  end

  def check_user
    redirect_to(root_url) unless @user == current_user
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FakeBnbV</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/_booking-form.html.erb
<%= simple_form_for @booking do |form| %>
  <div class="row justify-content-center">
    <div class="col-6 colored-border-right">
      <div class="text-center justify-content-center">
      
<%= form.input :start_date, label: "Début de la location",
            as: :string,
            input_html: { data: { controller: "datepicker" }, class: "field_style", } %>
                  </div>
    </div>
    <div class="col-6 ps-3">
<%= form.input :end_date, label: "Fin de la location",
            as: :string,
            input_html: { data: { controller: "datepicker" }, class: "field_style", } %>
            </div>
            </div>
<%= form.hidden_field :product_id, value: params[:id] %>
  <div class="row justify-content-center mt-2">
    <div class="col-12">
      <div class="text-center d-flex justify-content-center">
  <%= form.button :submit, "Réserver", class: "resa-button" %>
      </div>
    </div>
  </div>

<% end %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-4">
        <%= link_to product_path(product.id), class: "text-decoration-none text-dark" do %>
          <div class="card-trip">
            <%= image_tag(product.image_link, alt: product.title) %>
            <div class="card-trip-infos">
              <div>
                <h2><%= product.title %></h2>
                <p><%= product.description %></p>
              </div>
              <h2 class="card-trip-pricing pt-2"><%= product.price %>$ per day</h2>
              <%= image_tag User.find(product.user_id).photo, class: "card-trip-user avatar-bordered" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container pt-4 pb-4">
  <div class="col-10 mx-auto">
          <div class="card-trip_show">
            <%= image_tag(@product.image_link, alt: @product.title) %>
            <div class="">
<div class="mt-3">
  <div class = "row">
    <div class="col-6 pe-5">
  <h1 class="pb-3 colored-border-bottom"><%= @product.title %></h1>
  <p><%= @product.description %></p>

</div>
    <% if current_user && current_user.id == @product.user_id %>
        <div class = "col-6 reservation-box">
          <div class="row justify-content-center">
            <div class=" espace d-flex">
            <h3><%= @product.price %>€</h3> <p class ="p-1"> par jour</p>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-12">
              <div class="text-center d-flex justify-content-center mt-3">
          <h6>Ceci est votre personnage.</h6>
          </div>
          </div>
          </div>
          <div class="row justify-content-center mt-2">
            <div class="col-6 ps-5">
              <div class="text-center d-flex justify-content-center">
            <%= link_to "Modifier", edit_product_path(@product), class: "resa-button mx-auto text-center" %>
            </div>
            </div>
            <div class="col-6">
              <div class="text-center d-flex justify-content-center">
            <%= link_to 'Supprimer', delete_product_path(@product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-button mx-auto text-center" %>
            </div>
            </div>
            </div>
          </div>
    <% else %>
      <div class = "col-6 reservation-box">
            <div class="row justify-content-center">
            <div class=" d-flex ">
            <h3><%= @product.price %>€</h3> <p class ="p-1"> par jour</p>
            </div>
          </div>
          <%= render 'booking-form' %>
      </div>
    <% end %>
  </div>
</div>
  </div>
</div>
</div>
    

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <i class="fa-solid fa-heart resize" style="color: #232323;"></i>
          </li>
          <div class="cont d-flex align-items-center justify-content-center">
            <li class="nav-item dropdown">
              <div class="col-12">
                <i class="fa-solid fa-bars size"  id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #ffffff;"></i>
                <a href= <%= user_path(current_user.id)%> class="avatar">
                  <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
                </a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <!--- 
                  <%= link_to "Action", "#", class: "dropdown-item" %>
                  <%= link_to "Another action", "#", class: "dropdown-item" %> --->
                  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                </div>
              </div>
            </li>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container d-flex">
  <div class="col-6 mx-auto mt-3 text-center">
    <% if @user.photo? %>
      <%= image_tag @user.photo, alt: "User Photo", class: "avatar-large-profil" %>
    <% end %>
    <h2 class="colored-border-bottom pt-3 pb-4 thin"><%= @user.username %></h2>
    <% if @user.description? %>
      <h5 class="x-thin"><%= @user.description %></h5>
    <% end %>
  </div>
<div class="container ms-2 mt-3 resa-user">
    <div class="text-center">
        <h3>Reservations</h3>
    </div>
    <div class="row">
        <% @bookings.each do |booking| %>
            <div class="col-6">
                <div class="card-trip">
                    <%= image_tag booking.product.image_link, alt: "Product Photo" %>
                    <div class="card-trip-infos">
                        <div class="col-8">
                            <h5 class="font-size-medium"><%= booking.product.title %></h5>
                            <p><%= booking.start_date %> - <%= booking.end_date %></p>
                        </div>
                        <h2 class="card-trip-pricing pt-2 text-center"><%= booking.product.price %>$ per day</h2>
                        <%= image_tag User.find(booking.product.user_id).photo, class: "card-trip-user avatar-bordered" %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

  <!---<div class="row">
    <div class="container">
    <% @bookings.each do |booking| %>
      <div class="col-6">
          <div class="card-trip">
            <%= image_tag(booking.product.image_link, alt: booking.product.title) %>
            <div class="card-trip-infos">
              <div>
                <h2><%= booking.product.title %></h2>
                <p><%= booking.product.description %></p>
              </div>
              <h2 class="card-trip-pricing pt-2"><%= booking.product.price %>$ per day</h2>
              <%= image_tag User.find(booking.product.user_id).photo, class: "card-trip-user avatar-bordered" %>
            </div>
          </div>
      </div>
    <% end %>
    </div>
  </div>